
[package]
name = "solana-sdk-bpf-utils"
version = "0.17.0"
description = "Solana BPF SDK Rust Utils"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
solana-sdk-bpf-types = { path = "../solana-contract-types" }
