[dependencies.compiler_builtins]
path = "../../bpf-sdk/dependencies/rust-bpf-sysroot/src/compiler-builtins"
features = ["c", "mem"]

[target.bpfel-unknown-unknown.dependencies]
alloc = { path = "../../bpf-sdk/dependencies/rust-bpf-sysroot/src/liballoc" }
