[package]
name = "solana-sdk-bpf-types"
version = "0.17.0"
description = "Solana BPF SDK Rust Types"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"
